# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_emu.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 20, 751, 181))
        self.label.setText("")
        self.label.setObjectName("label")
        self.pushButton_arrow_left = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_arrow_left.setGeometry(QtCore.QRect(550, 100, 75, 23))
        self.pushButton_arrow_left.setObjectName("pushButton_arrow_left")
        self.pushButton_arrow_right = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_arrow_right.setGeometry(QtCore.QRect(660, 100, 75, 23))
        self.pushButton_arrow_right.setObjectName("pushButton_arrow_right")
        self.pushButton_arrow_up = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_arrow_up.setGeometry(QtCore.QRect(610, 70, 75, 23))
        self.pushButton_arrow_up.setObjectName("pushButton_arrow_up")
        self.pushButton_arrow_down = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_arrow_down.setGeometry(QtCore.QRect(610, 130, 75, 23))
        self.pushButton_arrow_down.setObjectName("pushButton_arrow_down")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_arrow_left.setText(_translate("MainWindow", "˂"))
        self.pushButton_arrow_right.setText(_translate("MainWindow", "˃"))
        self.pushButton_arrow_up.setText(_translate("MainWindow", "˄"))
        self.pushButton_arrow_down.setText(_translate("MainWindow", "˅"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
